name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14

      - name: Prepare Distribution Folder
        run: |
          mkdir -p dist
          emcc main.c -o dist/index.html \
            --shell-file shell_minimal.html \
            -s ASYNCIFY \
            -s NO_EXIT_RUNTIME=1 \
            -s FORCE_FILESYSTEM=1 \
            -idbfs \
            -s "EXPORTED_RUNTIME_METHODS=['ccall', 'FS_syncfs']"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages